### ISSUE TITLE
rdiff inefficient for zero sized signatures.

### ISSUE THREAD

**Issue by vps2fast** [librsync/librsync#13]
Hello!

I tried to use rdiff with zero sized signatures (with correct header but without any literals/copy items) and rdiff delta for this signatures produce bunch of cpu consumption and need so much time.

**Comment by dbaarda** [comment]
I think this might be much better than it was now. There have been a large number of improvements since this bug was filed that should mean it's heaps faster.

There is one tiny thing that could be done to make this even faster; use a "slack delta" if there are no blocks. This will mean it bypasses rollsum calculation and just emits literal commands for each input buffer.

I can do this pretty easily... I'll put together a merge request.

**Comment by dbaarda** [comment]
This is not a correctness bug, but a performance inefficiency. It works, it just needlessly generates rollsums to match against an empty hash table.

I'm going to fix this by making it do a "slack delta" for zero sized signatures. Pull request on the way.
