### ISSUE TITLE
Folder sync example

### ISSUE THREAD

**Issue by vacky11** [librsync/librsync#149]
Is there a example code which shows how to copy all the files from a source folder to destination folder, ignoring the existing files in destination folder using librsync?

**Comment by dbaarda** [comment]
librsync is a library for doing rsync style signature/delta/patch operations on files. The rdiff utility included with it is an example application that can do this for a single file. 

In theory you could write a script invoking rdiff multiple times to achieve what you want, but a better idea is to use an existing application that uses librsync to do this for you.

There are multiple applications that use librsync for doing this. Just looking in Debian bullseye for packages that depend on librsync2 I see the following possibilities; burp, csync2, and duplicity.

Finally, what you are probably looking for is rsync, the original utility for efficiently updating directories over the network that inspired librsync. Note rsync does not use librsync, since it came before librsync.

I hope that answers your question. I'm closing this now.
