### ISSUE TITLE
Multiple "ISO C does not support the ‘I64’ ms_printf length modifier" warnings with MinGW-w64

### ISSUE THREAD

**Issue by Adsun701** [librsync/librsync#184]
With commit 0388468200ba18705c88e723893e19fabd5ba967, I get [multiple warnings](https://gist.github.com/Adsun701/bbfc449097a2e727df079948e6cba0f0) when building librsync with the MinGW-w64 runtime.

**Comment by dbaarda** [comment]
I'm pretty sure the problem is in the CMakeLists.txt here;

https://github.com/librsync/librsync/blob/56d6182ca0c708db8f913de5ea3d20920223a0c5/CMakeLists.txt#L100

Interacting with the recent addition of `-std=c99 -pedantic` to try and ensure C99 compliance here.

https://github.com/librsync/librsync/blob/56d6182ca0c708db8f913de5ea3d20920223a0c5/CMakeLists.txt#L137

The CMake testing around setting HAVE_PRINTF_Z which indicates printf support for `%zu` format specifiers is complicated because of windows. The only way to check for support is using `check_c_source_runs()`, which doesn't work when cross-compiling. Also apparently some windows compilers do support it, but spit out warnings when using it (possibly because C++ support for it was questionable). It would be nice if there was some way to narrow down exactly when it's not supported, perhaps by checking for particular compilers or something, not just "WIN32".

The `%zu` format specifier is apparently C99 standard, so in keeping with our "require C99" approach we could just drop all this and always assume it's supported.

I'd be happy to accept pull requests that fix this.
