### ISSUE TITLE
librsync 2.3.0's tests/rdiff_bad_option.sh uses bash on shebang without any bash-specific code

### ISSUE THREAD

**Issue by mandree** [librsync/librsync#199]
Greetings,

trying to "ninja check" (ctest) on FreeBSD, I figured that the tests/rdiff_bad_option.sh file is missing from the official distribution tarball, https://codeload.github.com/librsync/librsync/tar.gz/v2.3.0?dummy=/librsync-librsync-v2.3.0_GH0.tar.gz

Please make sure that such tarballs, when unpacked, are self-contained also for "ninja check" tests. Thank you.

**Comment by dbaarda** [comment]
I don't fully understand how that could happen yet, but I'll figure it out and fix it.

**Comment by dbaarda** [comment]
It looks like it is there in the official tarball;

$ tar -tf Downloads/librsync-2.3.0.tar.gz | grep bad_option 
librsync-2.3.0/tests/rdiff_bad_option.sh

It also appears to be there in the tarbal you linked to;

$ tar -tf Downloads/librsync-2.3.0\ \(2\).tar.gz | grep bad_option
librsync-2.3.0/tests/rdiff_bad_option.sh

Are you sure something else is not going on?

**Comment by dbaarda** [comment]
Did you perhaps not run cmake with the right args for using ninja. Our travis check runs it with `-G Ninja`... check it here;

https://travis-ci.org/github/librsync/librsync/jobs/687715810

**Comment by dbaarda** [comment]
I looked at the bug you linked in #198 and the following comment seems to suggest the problem was your psvn setup lost the executable permission off this file;

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245514#c16

I've checked and it's definitely executable in the tarball;

$ tar -tvf Downloads/librsync-2.3.0.tar.gz | grep bad_option
-rwxrwxr-x root/root      1055 2020-04-07 16:57 librsync-2.3.0/tests/rdiff_bad_option.sh

So I suspect this was a problem at your end that has now been resolved. Closing this as fixed. Feel free to re-open if I've misunderstood and there is a genuine problem in librsync that needs fixing.

**Comment by mandree** [comment]
Thanks for the feedback. I figured it's the shebang `#! /bin/bash -ex` line that caused a "file not found" error, not the missing file. Switching to /bin/sh fixes the issue.
(FreeBSD does not install bash by default, and if it installs, it does not go into /bin, but into /usr/local/bin). 

A patch such as this fixes the issue and should be suitable for upstream inclusion:
 * [tests_rdiff__bad__option.sh.patch](https://github.com/librsync/librsync/files/4639974/patch.txt)

```
--- tests/rdiff_bad_option.sh.orig	2020-04-07 06:57:48 UTC
+++ tests/rdiff_bad_option.sh
@@ -1,1 +1,1 @@
-#! /bin/bash -ex
+#! /bin/sh -ex

```

**Comment by dbaarda** [comment]
I'm going to find and fix all uses of bash... reopening this until it's done.
