### ISSUE TITLE
Requirement for CMake 3.6 breaks RHEL/CentOS 6 and 7

### ISSUE THREAD

**Issue by robert-scheck** [librsync/librsync#203]
With librsync 2.3.1, you've bumped th CMake requirement to 3.6, which breaks building librsync with RHEL/CentOS 6 and 7, which are both having CMake 2.8.12.2.

I kindly would like to ask hereby to lower the requirement again, otherwise RHEL/CentOS 6 and 7 will be either stuck on librsync 2.3.0 or librsync might be removed at a point in the future from the EPEL 6 and 7 repositories (including tools linking against librsync) as it's then maybe unmaintainable on downstream side.

```
/usr/bin/cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON .
-- The C compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at CMakeLists.txt:20 (cmake_minimum_required):
  CMake 3.6 or higher is required.  You are running version 2.8.12.2
-- Configuring incomplete, errors occurred!
```

**Comment by robert-scheck** [comment]
Fortunately there was a non-default CMake 3.6.1 in EPEL 6 for RHEL/CentOS 6 that seems to do the trick, so please do not bump the CMake requirement again before the end of the year (that's when RHEL/CentOS 6 reaches EOL).

For RHEL/CentOS 7 there is even a non-default CMake 3.17.2 in EPEL 7, so please do not bump your requirement higher than that, otherwise the initial conclusion could still happen.

**Comment by dbaarda** [comment]
@robert-scheck : sorry for nearly breaking CentOS. I'm glad you found a solution.

For the record, the change to requiring CMake 3.6 was not made arbitrarily or lightly. It came in response to a sequence of platform compatibility problems for other platforms.

The first thing was #186 which added using CMake's PkgConfig to find popt on platforms where it had been linked with iconv.

Next came #198 where this PkgConfig usage broke things on FreeBSD. It turns out we were using it wrong, and it mostly worked by accident when it worked. In digging around the internet for docs/examples on using PkgConfig I came to the conclusion that the only way to make it work correctly was to use it's IMPORTED_TARGET feature, which was only added in CMake v3.6.

Before I did this change I did check just how old v3.6 was, and found that even our years old Xenial travis testing platform had v 3.12, so I assumed it would be OK.

If this really is a problem still, I think I know how we could make it work with older CMake versions. I could make the use of PkgConfig conditional on CMAKE_VERSION being NOT VERSION_LESS than 3.6. This would however break for platforms with older CMake versions AND popt linked to iconv.
