### ISSUE TITLE
Delta is larger than expected

### ISSUE THREAD

**Issue by ashf** [librsync/librsync#211]
System: Windows 10. I build the library as a static x86 windows library. Was able to link it to my project.

Issue: Delta file is much much larger than expected.

Assume I have a text file: sample.txt

Steps taken in code:
- Create signature of sample.txt
`rs_sig_file("sample.txt", "sample.sig", 0, -1, RS_RK_BLAKE2_SIG_MAGIC, NULL);`
- Load signature
`rs_loadsig_file("sample.sig", &signature, NULL);`
- Create Delta
`rs_build_hash_table(signature);`
`rs_delta_file(signature, "sample.txt", "sample.delta", NULL);`

The resulting Delta is effectively the same size as sample.txt. I expected the Delta to be close to 0KB, since the sample.txt didn't change between signature and delta creation. Am I doing something wrong, or is this expected behavior?

**Comment by dbaarda** [comment]
This is almost certainly due to windows special treatment of text files, where it does automatic "\r\n" -> "\n" translation on reading/writing.

Note the `rs_sig_file()` etc methods don't take a string filename, they take an open `FILE` object, so I'm assuming your code snippet above is simplified and you've omited the code where you open the file. On windows, how you open the file matters.

In `librsync.h` we now export a helper function `rs_file_open()` which ensures the file is opened in binary mode on windows by doing this; 

https://github.com/librsync/librsync/blob/d1938c387e86ab5bbf7cb2e84244229c5bbd5ebf/src/fileutil.c#L89

If you use that helper method to open the files it should work.

If that doesn't help, I'd need to investigate further.

**Comment by ashf** [comment]
I am already using `rs_file_open()` method. Here's a larger code snippet:

```
FILE* basis_file = rs_file_open(basis_filename.c_str(), "r", false);
FILE* signature_file = rs_file_open(signature_filename.c_str(), "w+", true);

auto ret = rs_sig_file(basis_file, signature_file, 0, -1, RS_RK_BLAKE2_SIG_MAGIC, NULL);

rs_file_close(basis_file);
rs_file_close(signature_file);

if (ret != RS_DONE) {
    return false;
}
return true;
```

**Comment by dbaarda** [comment]
You need to specify binary in the mode by using "rb" or "wb". You probably don't want "wb+" for the sig file as you don't need to read it, just write it.

Note the `_setmode()` thing inside `rs_file_open()` is how it switches stdin or stdout to binary mode. When opening actual files it needs the "b" in the mode.

**Comment by ashf** [comment]
> You need to specify binary in the mode by using "rb" or "wb". You probably don't want "wb+" for the sig file as you don't need to read it, just write it.

That was it. Thanks!
