### ISSUE TITLE
rs_free_sumset can cause HEAP CORRUPTION DETECTED crash

### ISSUE THREAD

**Issue by ashf** [librsync/librsync#214]
System: librsync 2.3.2, Windows 10 (VS2019 Debug Build). I build the library as a static x86 windows library. Was able to link it to my project.

Issue: Calling rs_free_sumset can crash with HEAP CORRUPTION DETECTED (this only happens for certain text files that I create signatures for, as of now I can't determine what identifies these files as being problem files until it crashes). The delta file created is empty when the crash occurs.

The actual crash is on the following line:
`free(t->k_bloom);`
![image](https://user-images.githubusercontent.com/6597733/94692122-2b85bb80-0300-11eb-93b4-6c49da7e0789.png)

Steps taken in code (there's some other non-relevant code abstracted from these steps):

Function A reads signature file:
```
FILE* signature_file = rs_file_open(signature_filename.c_str(), "rb", false);

// read file into memory
rs_signature_t* signature;
auto ret = rs_loadsig_file(signature_file, &signature, NULL);

// close file
rs_file_close(signature_file);

return signature;
```
Function B creates delta from signature passed into it:
```
// open files
FILE* basis_file = rs_file_open(basis_filename.c_str(), "rb", false);
FILE* delta_file = rs_file_open(delta_filename.c_str(), "wb", true);

// compute delta file
auto rs_ret = rs_build_hash_table(signature);
rs_ret = rs_delta_file(signature, basis_file, delta_file, NULL);

// deallocate signature
rs_free_sumset(signature);

// close files
rs_file_close(basis_file);
rs_file_close(delta_file);
```

signature contents right before crash:
![image](https://user-images.githubusercontent.com/6597733/94694691-18c0b600-0303-11eb-8fde-1f25610ba90a.png)

**Comment by ashf** [comment]
Update... A pattern I've noticed is that this crash occurs when the signature is created from smaller text files (~1KB or smaller)

**Comment by dbaarda** [comment]
I'm pretty sure this was found and fixed in #213 so it should be fixed in master.

I need to make a new release with that an other fixes.

**Comment by ashf** [comment]
That looks to be exactly the issue. Thank you. I hadn't looked through the PRs before posting this issue. Consider my issue resolved.

**Comment by ashf** [comment]
Curious, why was this not an issue for me when building in Release?

**Comment by dbaarda** [comment]
It depends exactly on what you mean by "building in Release", but if you mean v2.3.1, then I'm not sure.

The bloom filter was introduced in v2.3.1 and it looks like this problem has been there ever since. I was sure I had code that ensured the hashtable size was at least 8 which would have avoided this problem, but it looks like I never actually implemented it.

So if this problem doesn't appear in v2.3.1, then my best guess is that the problem was still there, but something in the improved windows compatibility in #208 made it so that MSVC could actually detect it. Or perhaps your compiler has recently added extra checking for this.

I suspect that this problem actually triggering something would depend on what calloc() does for a zero size. The docs say "if nmemb or size is 0, then calloc() returns either NULL, or a unique pointer value  that  can  later be successfully passed to free()".

If it returns NULL, then we would have got NULL de-referencing errors when the bloom filter was being populated, so it must be doing the latter. If it does the latter, then it depends where that pointer points. It looks like your compiler points it at a pre-initialized piece of memory after the heap, and then at free() checks if it's been changed. Note if it didn't check, then the program would just work as intended...

Under linux it might do something similar, but I've only had Windows users report this. So it may or may not have worked by accident on other platforms.
