### ISSUE TITLE
rsync vs network speed

### ISSUE THREAD

**Issue by proTerm** [librsync/librsync#235]
Do we have a rule of thumb when it is worth to use rsync to patch files over network vs. transfer the whole file without using librsync?

For example I would be interested in something for a 1GB file, 10GB, 100MB etc.?

Some rough calculations of a 1GB file:
- Pure transfer: 8-20secs
is transferred over the Gigabit Ethernet in min. 8secs (max 125MB/s), or in 20secs (max. 50MBit/s) 

- librsync: 13 sec
-- transfer the file name 1 sec
-- calculating the sig file 4 secs
-- transfer the sig file 1 sec
-- calculating the delta 4 secs
-- transfer the delta file 2 secs
-- patch the file 1sec

**Comment by sourcefrog** [comment]
The specific answer is going to depend on the CPU, memory bandwidth, IO bandwidth, and network bandwidth of the two machines. If you want a number in seconds the best thing is to measure a realistic case on your own equipment.

Generally speaking rsync (and librsync) will have an large advantage when the recipient has a basis file that is fairly similar, because they can avoid sending the common sections.

If the recipient has no basis file, or an empty basis, there's very little extra overhead.

If the recipient has a large basis with no data in common then the extra overhead is primarily the time for it to read the whole of that basis file. (It also has to send the signature and the recipient has to match against it, but that will normally be relatively cheap.)

**Comment by proTerm** [comment]
Hi,
sorry, your answer doesnt help. I didnt want seconds, I wanted a realistic view of when librsync is worth using and when not.

I claim, librsync doesn't bring any added value, if the creation of the sigs and delta takes significant amount of time. In todays high speed networks, if the creation of the sigs and deltas takes similar or more time than the transport of the file itself, there is no use of librsync anymore. Correct me if Im wrong please?

Further, I read somewhere, that delta are always generated on an encrypted FileSystem, even if the files are same. Has this been a removed problem, or is it still an issue?

**Comment by Salamek** [comment]
@proTerm are you by any chance by one of those game devs that are able to release 5GiB update to fix one broken 500kB texture? :D (there is a lot of those out there in the wild lol, BTW this is also an example of "realistic view of when librsync is worth using ")

**Comment by sourcefrog** [comment]
rsync algorithms are generally worth using when:
* significant parts of the file are the same, AND
* the network is slower or more expensive than local disk IO

Although networks are now faster, disks and CPUs are also faster, and files are bigger. So the same tradeoff applies.

For example a typical SSD can read at say 1000MB/s and a cable broadband link can download at say 100Mbit/s, 10MB/s. For a 1GB file it is clearly worth spending 1s to read it off disk to reduce network traffic, since downloading the whole thing would take 100s.

You can do similar math for other situations such as cell data or high-bandwidth datacenter links. For cell data typically the user pays per MB, which is an additional incentive to do some local work to avoid network IO. In a datacenter context the links can be very fast compared to local IO, but also typically the bandwidth is still scarce, and it's shared between machines and services, so people still care about not wasting it.

> Further, I read somewhere, that delta are always generated on an encrypted FileSystem, even if the files are same. Has this been a removed problem, or is it still an issue?

Someone is confused there. Applications like rsync (or vim or whatever) that read data off encrypted filesystems obviously see the clear text and work just the same.

Perhaps they were talking about transferring images of encrypted disks or VMs. If you're transferring different snapshots of the same VM it's still useful as encryption only rewrites the affected blocks.

If you have several independently-generated encrypted disk images that store the same content but with different keys or IVs, they'll look entirely different.

**Comment by proTerm** [comment]
> rsync algorithms are generally worth using when:
> 
>     * significant parts of the file are the same, AND
> 
>     * the network is slower or more expensive than local disk IO
> 
> Although networks are now faster, disks and CPUs are also faster, and files are bigger. So the same tradeoff applies.
> 
> For example a typical SSD can read at say 1000MB/s and a cable broadband link can download at say 100Mbit/s, 10MB/s. For a 1GB file it is clearly worth spending 1s to read it off disk to reduce network traffic, since downloading the whole thing would take 100s.
> 
Just for the arithmetic: it would take 10s with 100Mbit/s ...

Why dont we make an experiment: Could you please try it on your computer, how long does it take for a 100MB, 1GB, 5GB file the generation of the sigs and deltas (the patch time should be neglectable) ?

**Comment by dbaarda** [comment]
> > Although networks are now faster, disks and CPUs are also faster, and files are bigger. So the same tradeoff applies.
> > For example a typical SSD can read at say 1000MB/s and a cable broadband link can download at say 100Mbit/s, 10MB/s. For a 1GB file it is clearly worth spending 1s to read it off disk to reduce network traffic, since downloading the whole thing would take 100s.
> 
> Just for the arithmetic: it would take 10s with 100Mbit/s ...

Err, a 1GByte file transferred at 100Mbits/sec, AKA 10MBytes/sec, would take ~100sec.

> Why dont we make an experiment: Could you please try it on your computer, how long does it take for a 100MB, 1GB, 5GB file the generation of the sigs and deltas (the patch time should be neglectable) ? (Something like @pavel-odintsov made[ here](https://github.com/librsync/librsync/issues/6))

In the last bunch of speed tests I ran for v2.3.2 with all default blocksize/etc settings, using whatever hardware github actions uses, it took 3.18sec to calculate a sig, 16.42secs to calculate a delta, and 2.13secs to apply the patch, for a total of less than 22secs. That was a test case using 1GB files where 50% of the file was different, so the delta was 50% of the size, or ~500MBytes. That brings the total transfer time down to 50secs to transfer the delta, + 22 secs for sig+delta+patch, = 72 seconds, a saving of 28%.

And this case is probably your typical worst case. For more typical cases where there are less changes, calculating the delta is much faster, and it is much smaller. If there was only 25% changes, the delta would take about 9secs to calculate and only 25secs to transfer, bringing it down to 40secs total, or a 60% saving of time. It gets better and better the smaller the delta.

**Comment by dbaarda** [comment]
I missed the sig transfer time, which you would have do for most typical applications. The sig was 1.2MBytes, so would take ~0.12sec to transfer that needs to be added to the total time, not enough to make a difference.

This also assumes you do every step serially. If time mattered, it would be trivial to stream the delta as it's generated, and stream the patch as it's applied, so the generation and patch happens in parallel with the transfer so they don't contribute at all to the overall time. This reduces the total time to less than 54 secs for the 50% changes case, or a 46% time saving, and less than 29secs or 71% time saving for the 25% changes case.

Depending on your application, you could have things like pre-calculated sigs or even deltas, further reducing the delay and overheads.

**Comment by dbaarda** [comment]
In summary, because the delta and patch calculation can happen in parallel with the delta transfer, provided the delta and patch calculations are faster than the delta transfer, the only time overhead is the sig calculation, and the total time is sig+R*T where R is the delta size ratio and T is time to just transfer the whole file. If the delta transfer is faster, then the total time becomes pegged to the sig+delta time.

For the 1GBytes file with 50% changes case, sig+delta is ~20secs, so you would need a transfer rate of 50MBytes/sec or ~500Mbits/sec for it to be faster to just transfer the file. For the 25% changes case, sig+delta is ~12secs, so you would need a transfer rate of 85Mbytes/sec or 850Mbits/sec for it to be faster to just transfer the file. For "empty deltas" you would need a link faster than 1.5Gbits/sec.

But speeding up transfers is also only one use-case for librsync. There are plenty of people using it to calculate deltas to save storage space.

**Comment by sourcefrog** [comment]
@proTerm your interactions here and in the [now-closed duplicate on Stack Overflow](https://stackoverflow.com/questions/69851506/when-is-it-worth-usng-for-network-file-transfer-librsync-vs-transferring-whole/69856151?noredirect=1#comment123551777_69856151) are verging on being hostile and accusatory, which is not OK. 

Please engage [respectfully](https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md).
