### ISSUE TITLE
rs_patch_file old <-> new file

### ISSUE THREAD

**Issue by proTerm** [librsync/librsync#236]
Overall Im seeing the pattern
`rs_patch_file(old_file, delta_file, new_file, ...);`
But why not only:
`rs_patch_file(old_file, delta_file, old_file, ...);`
i.e. patch directly the old_file ? Do you overwrite the `old_file` with the `new_file` after it (any worst/best practices to do it)?

**Comment by sourcefrog** [comment]
The short answer is no, that wouldn't make sense with `rs_patch_file`.

The reason is that when applying a patch, librsync writes sequentially to the new file and reads blocks from the old file in arbitrary order (as instructed by the patch.)

Therefore, the whole old file needs to exist for the entire duration of applying the patch. 

In this API the application level code is responsible for e.g. making a temporary new file and renaming the new file over the old file when patching is complete, if that's what it wants to do.

Conceivably someone could add a similar function that takes filenames rather than `FILE *`, creates a temp file, and renames on completion. (I'll defer to Donovan on whether that's really in scope, but it would not be too complicated.)

---

Beyond this, some applications may really want to edit a file in place rather than write-and-rename, perhaps because the file is very large relative to the changes and relative to disk space or bandwidth. Taking this approach means dealing with the possibility that the program stops halfway through patching the file, leaving it in an indeterminate state, which is a bit more complex than just having an abandoned temporary file.

I think it would be possible to write a patch-application function for librsync's delta format that works in-place, but it would get a bit complicated. librsync's delta can express, for example, that the second half of the file swaps with the first half, which would be complicated to apply in-place, and seems difficult to do safely in the face of unexpected termination.

To support in-place edits it's probably better to use a different format designed for that purpose, perhaps just simply instructions to overwrite given ranges of the file, without any copy/move instructions. 



It's also possible to apply a binary patch by mutating a single file in place: copy the regions that are retained, and insert new data where it's needed. This isn't implemented in librsync. This means dealing with the failure mode where the program is interrupted leaving the file half-updated, which is
