### ISSUE TITLE
1) sig file -> size 0 ?   2) static/dynamic lib Windows ?

### ISSUE THREAD

**Issue by proTerm** [librsync/librsync#238]
Is this correct, that when the `sig size is 0,` the file has _no similarities_ ?

Are there any issues with building static (dynamic) rsync libs on Windows?

**Comment by dbaarda** [comment]
The sig size depends on the original file size and block size used, and can never be zero due to the file header.

Do you mean the delta size? The delta can also not be zero due to headers, but the smaller the delta the *more similar* the files are. If there are zero differences the delta will still include the 4 byte header and a 4~17 byte copy command. So a zero-difference delta will be about 8~20 bytes.

See https://github.com/librsync/librsync/blob/master/doc/formats.md for details.

**Comment by dbaarda** [comment]
Oh yeah, Windows DLLs should be fine, and our github actions includes a full test and build of rdiff using an rsync.dll as you can see here;

https://github.com/librsync/librsync/runs/4360707214?check_suite_focus=true

**Comment by proTerm** [comment]
@dbaarda my windows question was primarly about static libs on windows? Does this function and how ?

**Comment by dbaarda** [comment]
It would mean something went wrong, because even an empty file sig need to have the sig-file header, which is about 12 bytes.

Note on many operating systems writes are not flushed until the file is closed.

**Comment by proTerm** [comment]
@dbaarda Could you perhaps interpret the following:
`auto ret_code = rs_patch_file(old_file, delta_file, patched_file, NULL);`
`patched_file is 0` bytes and `ret_code == RS_DONE` ?

**Comment by proTerm** [comment]
@dbaarda How do you know there is no difference between two files?

**Comment by dbaarda** [comment]
> @dbaarda How do you check there is no difference in the content of two files? (regardless timestamps (and permissions))

Do you mean in general, or from a librsync patch file, or maybe even a librsync signature file?

If you mean in general, and you have local access to both files, then a direct per-byte comparison is cheapest, since you can bail at the first difference and avoid fully scanning both files unless they are identical. If you don't have local access to both files, then comparing the whole-file hash values is pretty easy and there are cmdline tools like md5sum that you can use for this.

If you mean from a librsync patch file, then its not exactly trivial. The smaller the patch the smaller the differences, but even a zero-diff patch file is non-zero size since it includes the header and copy instructions. The exact size of a zero-diff file depends on the size of the original file, since the copy instructions depend on the size of the copy. You could read the patch and check that it includes only copy instructions, but even then there is no guarantee it was identical since truncated or re-arranged data aligned exactly on a block boundaries will also give you only copy instructions.

If you mean from a librsync signature file, you could diff the signature files, provided they were generated using identical arguments (block-size, checksum, etc), and identical sig's means identical files. This can even be short-circuited, bailing out at the first diff, so you can avoid reading the whole file unless they are identical.
