### ISSUE TITLE
Infinite loop for truncated signature or delta files.

### ISSUE THREAD

**Issue by paulharris** [librsync/librsync#32]
This might be related to #29 
I was investigating why delta files seem to have additional characters on the end when generating deltas of identical files...

With the current rdiff,

``` bash
echo "Hello world" > input
rdiff signature input sig
rdiff delta sig input delt
rdiff patch input delt output
# all is fine
# time to hang the process, truncate the delta file
dd if=delt of=delt2 bs=1 count=1
rdiff patch input delt2 output
# HANG, infinite loop somewhere
# Note that when the delta file is big enough, THEN the problem is handled properly
dd if=delt of=delt2 bs=1 count=4
rdiff patch input delt2 output
librsync: ERROR: (librsync) patch job failed: unexpected end of input
librsync: ERROR: unexpected end of input
```

**Comment by dbaarda** [comment]
I had a quick look at this, checking with debug and tracing on and it gets stuck doing this;

rdiff: (rs_job_new) start patch job
rdiff: (rs_scoop_readahead) couldn't satisfy request for 4, scooping 0 bytes
rdiff: (rs_scoop_input) resized scoop buffer to 8 bytes from 0
rdiff: (rs_scoop_input) accepted 1 bytes from input to scoop
rdiff: (rs_infilebuf_fill) seen end of file on input
rdiff: (rs_scoop_readahead) data is present in the scoop and must be used
rdiff: (rs_scoop_input) accepted 0 bytes from input to scoop
rdiff: (rs_scoop_readahead) still have only 1 bytes in scoop
rdiff: (rs_scoop_readahead) data is present in the scoop and must be used
rdiff: (rs_scoop_input) accepted 0 bytes from input to scoop
rdiff: (rs_scoop_readahead) still have only 1 bytes in scoop
...

The problem is in rs_scoop_readahead() which doesn't check that the input is at eof before it completes a readahead. I'll try and put together a fix.

**Comment by dbaarda** [comment]
I've just submitted pull request #119 to fix this problem. I'll probably submit it soon unless someone encounters a problem with it.

Note this problem could also affect truncated signatures.
