### ISSUE TITLE
Question: License

### ISSUE THREAD

**Issue by mbrt** [librsync/librsync#56]
I'm starting to work on bindings for this library in [Rust](https://www.rust-lang.org/). The problem is the following:
* linking between Rust libraries is static;
* linking between a Rust library and a C library can be static or dynamic. However dynamically linking means that the library (and thus all the derivative projects) needs to be rebuilt for every linux distribution, osx and windows systems (because librsync needs to be present in the system, and could be different);
* the vast majority of Rust libraries are licensed under MIT.

So, if I want to provide the best experience to library users I should link librsync statically and provide a MIT license. However MIT and LGPL are not strictly compatible. So, to be pedantic I need to:
* link dynamically (and be not portable across distributions without rebuld);
* or be LGPL myself (and be poorly integrated in the Rust ecosystem).

I'm not a lawyer, but since I will provide sources on GitHub, package through [crates.io](https://crates.io/) I will be 100% open source. Is it a problem if the license is MIT?

Am I missing something? I don't know if I'm clear.

**Comment by sourcefrog** [comment]
Hi,

I think a Rust binding would be great, please let me know when you have something.

The intention of the LGPL on librsync is that people can use it in proprietary programs, but they have to make the source available to users, and to allow users to use a modified librsync in that program. 

> However dynamically linking means that the library (and thus all the derivative projects) needs to be rebuilt for every linux distribution, osx and windows systems (because librsync needs to be present in the system, and could be different);

I'm not quite sure what you mean by 'rebuilt for every linux distribution etc'. Rust binaries to the best of my knowledge already dynamically link to various system C libraries and so need to be rebuilt for different ABIs. If the librsync ABI is the same across linux systems (or OS X versions etc) then a new Rust binary should not be necessary.

I would also note that anyone shipping open source programs built from librsync is free to statically link it, because the user then has everything they need to modify and rebuild.

**Comment by mbrt** [comment]
Understood! So, I think it is safe to release the binding as MIT/Apache and the librsync part (unmodified, I think) with its own license.

BTW, Rust binaries link to a pretty old libc, and since libc is very serious about retro-compatibility, the result is that a Rust binary is portable as-is in the vast majority of Linux systems. However, librsync could be present in a system in different versions and even with different names (e.g. `librsync.so`, `librsync.so.2`, etc). So, the portability is decreased.

Thanks for the clarification.

**Comment by sourcefrog** [comment]
OK, thanks.

I suggest you highlight this in the docs for your binding. I'll be interested to see it, and in particular what buffer API feels natural in Rust.

**Comment by mbrt** [comment]
> I suggest you highlight this in the docs for your binding.

Of course!

You can follow the progress [here](https://github.com/mbrt/librsync-rs). I'm not sure about the name yet :)
