### ISSUE TITLE
Speed issues: Use larger buffer sizes.

### ISSUE THREAD

**Issue by pavel-odintsov** [librsync/librsync#6]
Hello!

Could you optimize rdiff tool performance? It's very slow and unusable in most cases =(

**Comment by paulharris** [comment]
This speed issue may be resolved with latest master, due to merge of improvements related to large files.

**Comment by dbaarda** [comment]
This bug was complaining about signature generation time, which is pretty simple file-read and checksum calculation work. It's unsurprising that setting buffer size larger than block size more than doubled his throughput.

That the CPU gets pegged doing md4sum calculations is unsurprising. I don't think much can be done to optimize the md4sum calculation. The best that can be done is parallelize the md4sum calculation so we can peg multiple CPU's :-) Also maybe the new blake2sums' are faster... dunno.

At the end he mentions delta calculation, which has been significantly improved with a new hashtable for large files since this bug was filed, though using 1M blocksize would have avoided problems with the old hashtable.

The idea of parallelizing signature generation is being tracked in #68.

The only thing left that this bug could do is have the buffer size default to something like 16x block size, not just 16K, if unspecified.

**Comment by dbaarda** [comment]
I've been thinking a little about the bufferlen settings and am about to do something about this.

The rs_inbuflen and rs_outbuflen vars are publicly visible/setable according to librsync.h. They primarily control the  rs_buffers_t size used by the whole-file API implemented in whole.c, but crucially rs_outbuflen  is also used by delta.c as the maximum size buffered/output per output-literal command.

In scoop.c librsync keeps it's own internal scoop_buf buffer that data is copied into for matching against (the double-copying this implies is another problem). In delta.c we always copy all the data in the input buffers to the scoop. This buffer grows by doubling size till it is large enough to contain a full block for matching against + the largest amount of miss data buffered for a single output-literal command + the full size of the next input buffer. This means it grows as large as the next power of 2 larger than rs_outbuflen + block_size+rs_inbuflen (note we could just pre-allocate the max needed size).

For rs_inbuflen it's only used for pre-fetching data to be copied into the scoop. After a match we always need at least a whole block of data to begin checking for matches again, so having rs_inbuflen < block_size is inefficient. 

For rs_outbuflen The maximum output the algorithm generates in a single iteration is the largest output-literal command (cmd bytes+literal data).

Should we use rs_outbuflen as the max size for buffering/outputing literal cmds? This makes it the only setting outside of the job_t struct that affects the delta output. Probably a better option would be to use a multiple of the block size. Using 4x blocksize and setting rs_inbuflen=blocksize means the scoop would grow large enough to fit 6xblocksize, which is probably OK.

**Comment by dbaarda** [comment]
After submitting #105 I believe everything mentioned in this bug is now addressed. I'm marking it closed.
