### ISSUE TITLE
the push-style API is not totally push-style

### ISSUE THREAD

**Issue by capr** [librsync/librsync#65]
rs_patch_begin() uses a callback to read the basis instead of I/O buffers. I guess a 3-way buffers structure is needed to solve this.

**Comment by mbrt** [comment]
The basis needs to be seekable. I think `librsync` deals with this fact by asking the caller to provide a sort of read and seek callback. So, a buffer addition is not enough. There is the need of a callback or some getter that informs you where to seek and how much to read. The current API implements it in a single callback.

**Comment by capr** [comment]
So it's a bit more involved but it might be worth a fix. The problem currently is that the API is not entirely push-style which means I cannot use it with coroutines in LuaJIT (because of a limitation of LuaJIT and callbacks which is also present in other ffi libraries of other languages btw), which leads to 3 options: 1) fix librsync's patch function so that the entire API is push-style, 2) re-implement patching in Lua, 3) reimplement rsync in Lua. (I ended up with option 3 and would probably do option 2 as well just so I can have a complete binding and also to compare speeds).

**Comment by mbrt** [comment]
Understood. However this would be a breaking change and I don't know if it'd be merged. Instead of re-implementing everything I suggest you to fork and try on your own to add this functionality. You can then bind your fork with LuaJIT. I think this is a faster (and maybe safer) approach.

**Comment by capr** [comment]
Sure, I would make a new function for that to keep compat. Any you're probably right about forking rsync for this, I might try that.

**Comment by dbaarda** [comment]
I'm curious, how would you implement a pure push-style API for seeks/reads from the basis file? What would it look like?

**Comment by dbaarda** [comment]
I'm curious because I'm looking at our push-style API for calculating delta's and its terribly inefficient, with lots of redundant memory copying. I was thinking a pure callback API would be much more efficient.

**Comment by dbaarda** [comment]
So rather than somehow make the patch API fully push-style, I've started experimenting with an entirely callback API in #209. This API would be more consistent than the current mixed push/callback API for patches, and it looks like it like it is already faster because of less buffer copies. With this change, the existing API can be implemented on top of the new callback API.

A pure push version of the patch API could also be implemented on top of this callback API, but it would probably look pretty strange, with the buffers object gaining a seek-offset field that the push-api patch operation would set to indicate the client needs to start pushing data from an offset in the basis file instead of from the delta.

I'm, going to consider Issue resolved as kinda infeasible/undesirable because how ugly/strange it would look. If someone really does need a pure push API they can file another bug with a proposal for what it would look like, and we could consider adding it after the callbackAPI is done.
