### ISSUE TITLE
migrate tests from bash

### ISSUE THREAD

**Issue by sourcefrog** [librsync/librsync#82]
Test drivers are currently mostly in bash, which makes it annoying to run them on Windows: probably possible, but they probably won't run by default for most people and they can easily break.  

It'd be better if those for C functionality switched to being directly in C.  Command-line tests I'm not sure: maybe C, or Python.

**Comment by dbaarda** [comment]
Note there is also mutate.pl which makes the tests dependent on perl, which should also go away.

**Comment by dbaarda** [comment]
Note with recent cleanups and the new github actions added in #225, Windows now has full build and testing of everything including rdiff. The current status is;

1. There are many unittests written as C executables using assert().
2. The rdiff integration tests all use `#!/bin/sh` so they run on systems without bash.
3. On windows the integration tests are run by explicitly executing them with 'bash', since it doesn't understand `#!` lines and has bash installed (at least it's installed by default on the github actions windows_latest platform).
4. The only remaining perl script is `tests/mutate.pl`. Interestingly the github actions windows_latest platform seems to also have perl installed, and it just works.

I think for integration tests running rdiff, using a shell makes sense, since it most closely emulates the real use-case of using it from the cmdline. While it's true that different platforms have different shells, we need to pick one so we don't have to replicate everything for different shells. It seems that `#!/bin/sh` is a pretty good lowest common denominator, and explicitly executing them with bash gives us a solution for Windows.

What might make sense is to use a test framework for executing cmdline integration tests, as I've considered for one of my other projects in https://github.com/dbaarda/LightLdapd/issues/8#issuecomment-848438153. In particular sharness might be worth using. However, there is no particular urgency to do this, and it is outside the scope of this issue.

It would be good to drop the last remaining perl script, but given that this doesn't seem to be posing a problem on any platforms right now, and replicating it's functionality in pure /bin/sh is rather hard. In any case, it's probably outside the scope of this bug.

So I'm going to declare this fixed.
